local:
  address: 0.0.0.0:9099

logger:
  maxSize: 32
  maxAge: 7
  maxBackup: 30
  compress: false
  level: 0
  serviceName: core_dump_http_server
  logPath: ./logs/core_dump_http_server.log
